# Generated by Django 4.0.4 on 2022-04-27 08:45

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_maincatigory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(default=shop.models.MainCatigory.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.maincatigory'),
        ),
    ]
